export const DB_PATH = __dirname + "../../../database.db"
export const DB_HOST = process.env.DB_HOST || "localhost"
export const DB_NAME = process.env.DB_NAME || "link_shortener"
export const DB_USER = process.env.DB_USER || "postgres"
export const DB_PASSWORD = process.env.DB_PASSWORD || "postgres"
export const JWT_SKEY = process.env.DB_USER || "jwt_sk_a7we&3j-123aa"
